// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package add

//go:generate minimock -i github.com/AndrejDubinin/review-assigner/internal/services/team/add.repository -o repository_mock_test.go -n RepositoryMock -p add

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/AndrejDubinin/review-assigner/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// RepositoryMock implements repository
type RepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddTeam          func(ctx context.Context, team domain.TeamDTO) (err error)
	funcAddTeamOrigin    string
	inspectFuncAddTeam   func(ctx context.Context, team domain.TeamDTO)
	afterAddTeamCounter  uint64
	beforeAddTeamCounter uint64
	AddTeamMock          mRepositoryMockAddTeam
}

// NewRepositoryMock returns a mock for repository
func NewRepositoryMock(t minimock.Tester) *RepositoryMock {
	m := &RepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddTeamMock = mRepositoryMockAddTeam{mock: m}
	m.AddTeamMock.callArgs = []*RepositoryMockAddTeamParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRepositoryMockAddTeam struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockAddTeamExpectation
	expectations       []*RepositoryMockAddTeamExpectation

	callArgs []*RepositoryMockAddTeamParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockAddTeamExpectation specifies expectation struct of the repository.AddTeam
type RepositoryMockAddTeamExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockAddTeamParams
	paramPtrs          *RepositoryMockAddTeamParamPtrs
	expectationOrigins RepositoryMockAddTeamExpectationOrigins
	results            *RepositoryMockAddTeamResults
	returnOrigin       string
	Counter            uint64
}

// RepositoryMockAddTeamParams contains parameters of the repository.AddTeam
type RepositoryMockAddTeamParams struct {
	ctx  context.Context
	team domain.TeamDTO
}

// RepositoryMockAddTeamParamPtrs contains pointers to parameters of the repository.AddTeam
type RepositoryMockAddTeamParamPtrs struct {
	ctx  *context.Context
	team *domain.TeamDTO
}

// RepositoryMockAddTeamResults contains results of the repository.AddTeam
type RepositoryMockAddTeamResults struct {
	err error
}

// RepositoryMockAddTeamOrigins contains origins of expectations of the repository.AddTeam
type RepositoryMockAddTeamExpectationOrigins struct {
	origin     string
	originCtx  string
	originTeam string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAddTeam *mRepositoryMockAddTeam) Optional() *mRepositoryMockAddTeam {
	mmAddTeam.optional = true
	return mmAddTeam
}

// Expect sets up expected params for repository.AddTeam
func (mmAddTeam *mRepositoryMockAddTeam) Expect(ctx context.Context, team domain.TeamDTO) *mRepositoryMockAddTeam {
	if mmAddTeam.mock.funcAddTeam != nil {
		mmAddTeam.mock.t.Fatalf("RepositoryMock.AddTeam mock is already set by Set")
	}

	if mmAddTeam.defaultExpectation == nil {
		mmAddTeam.defaultExpectation = &RepositoryMockAddTeamExpectation{}
	}

	if mmAddTeam.defaultExpectation.paramPtrs != nil {
		mmAddTeam.mock.t.Fatalf("RepositoryMock.AddTeam mock is already set by ExpectParams functions")
	}

	mmAddTeam.defaultExpectation.params = &RepositoryMockAddTeamParams{ctx, team}
	mmAddTeam.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAddTeam.expectations {
		if minimock.Equal(e.params, mmAddTeam.defaultExpectation.params) {
			mmAddTeam.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddTeam.defaultExpectation.params)
		}
	}

	return mmAddTeam
}

// ExpectCtxParam1 sets up expected param ctx for repository.AddTeam
func (mmAddTeam *mRepositoryMockAddTeam) ExpectCtxParam1(ctx context.Context) *mRepositoryMockAddTeam {
	if mmAddTeam.mock.funcAddTeam != nil {
		mmAddTeam.mock.t.Fatalf("RepositoryMock.AddTeam mock is already set by Set")
	}

	if mmAddTeam.defaultExpectation == nil {
		mmAddTeam.defaultExpectation = &RepositoryMockAddTeamExpectation{}
	}

	if mmAddTeam.defaultExpectation.params != nil {
		mmAddTeam.mock.t.Fatalf("RepositoryMock.AddTeam mock is already set by Expect")
	}

	if mmAddTeam.defaultExpectation.paramPtrs == nil {
		mmAddTeam.defaultExpectation.paramPtrs = &RepositoryMockAddTeamParamPtrs{}
	}
	mmAddTeam.defaultExpectation.paramPtrs.ctx = &ctx
	mmAddTeam.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmAddTeam
}

// ExpectTeamParam2 sets up expected param team for repository.AddTeam
func (mmAddTeam *mRepositoryMockAddTeam) ExpectTeamParam2(team domain.TeamDTO) *mRepositoryMockAddTeam {
	if mmAddTeam.mock.funcAddTeam != nil {
		mmAddTeam.mock.t.Fatalf("RepositoryMock.AddTeam mock is already set by Set")
	}

	if mmAddTeam.defaultExpectation == nil {
		mmAddTeam.defaultExpectation = &RepositoryMockAddTeamExpectation{}
	}

	if mmAddTeam.defaultExpectation.params != nil {
		mmAddTeam.mock.t.Fatalf("RepositoryMock.AddTeam mock is already set by Expect")
	}

	if mmAddTeam.defaultExpectation.paramPtrs == nil {
		mmAddTeam.defaultExpectation.paramPtrs = &RepositoryMockAddTeamParamPtrs{}
	}
	mmAddTeam.defaultExpectation.paramPtrs.team = &team
	mmAddTeam.defaultExpectation.expectationOrigins.originTeam = minimock.CallerInfo(1)

	return mmAddTeam
}

// Inspect accepts an inspector function that has same arguments as the repository.AddTeam
func (mmAddTeam *mRepositoryMockAddTeam) Inspect(f func(ctx context.Context, team domain.TeamDTO)) *mRepositoryMockAddTeam {
	if mmAddTeam.mock.inspectFuncAddTeam != nil {
		mmAddTeam.mock.t.Fatalf("Inspect function is already set for RepositoryMock.AddTeam")
	}

	mmAddTeam.mock.inspectFuncAddTeam = f

	return mmAddTeam
}

// Return sets up results that will be returned by repository.AddTeam
func (mmAddTeam *mRepositoryMockAddTeam) Return(err error) *RepositoryMock {
	if mmAddTeam.mock.funcAddTeam != nil {
		mmAddTeam.mock.t.Fatalf("RepositoryMock.AddTeam mock is already set by Set")
	}

	if mmAddTeam.defaultExpectation == nil {
		mmAddTeam.defaultExpectation = &RepositoryMockAddTeamExpectation{mock: mmAddTeam.mock}
	}
	mmAddTeam.defaultExpectation.results = &RepositoryMockAddTeamResults{err}
	mmAddTeam.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAddTeam.mock
}

// Set uses given function f to mock the repository.AddTeam method
func (mmAddTeam *mRepositoryMockAddTeam) Set(f func(ctx context.Context, team domain.TeamDTO) (err error)) *RepositoryMock {
	if mmAddTeam.defaultExpectation != nil {
		mmAddTeam.mock.t.Fatalf("Default expectation is already set for the repository.AddTeam method")
	}

	if len(mmAddTeam.expectations) > 0 {
		mmAddTeam.mock.t.Fatalf("Some expectations are already set for the repository.AddTeam method")
	}

	mmAddTeam.mock.funcAddTeam = f
	mmAddTeam.mock.funcAddTeamOrigin = minimock.CallerInfo(1)
	return mmAddTeam.mock
}

// When sets expectation for the repository.AddTeam which will trigger the result defined by the following
// Then helper
func (mmAddTeam *mRepositoryMockAddTeam) When(ctx context.Context, team domain.TeamDTO) *RepositoryMockAddTeamExpectation {
	if mmAddTeam.mock.funcAddTeam != nil {
		mmAddTeam.mock.t.Fatalf("RepositoryMock.AddTeam mock is already set by Set")
	}

	expectation := &RepositoryMockAddTeamExpectation{
		mock:               mmAddTeam.mock,
		params:             &RepositoryMockAddTeamParams{ctx, team},
		expectationOrigins: RepositoryMockAddTeamExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAddTeam.expectations = append(mmAddTeam.expectations, expectation)
	return expectation
}

// Then sets up repository.AddTeam return parameters for the expectation previously defined by the When method
func (e *RepositoryMockAddTeamExpectation) Then(err error) *RepositoryMock {
	e.results = &RepositoryMockAddTeamResults{err}
	return e.mock
}

// Times sets number of times repository.AddTeam should be invoked
func (mmAddTeam *mRepositoryMockAddTeam) Times(n uint64) *mRepositoryMockAddTeam {
	if n == 0 {
		mmAddTeam.mock.t.Fatalf("Times of RepositoryMock.AddTeam mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAddTeam.expectedInvocations, n)
	mmAddTeam.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAddTeam
}

func (mmAddTeam *mRepositoryMockAddTeam) invocationsDone() bool {
	if len(mmAddTeam.expectations) == 0 && mmAddTeam.defaultExpectation == nil && mmAddTeam.mock.funcAddTeam == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAddTeam.mock.afterAddTeamCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAddTeam.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AddTeam implements repository
func (mmAddTeam *RepositoryMock) AddTeam(ctx context.Context, team domain.TeamDTO) (err error) {
	mm_atomic.AddUint64(&mmAddTeam.beforeAddTeamCounter, 1)
	defer mm_atomic.AddUint64(&mmAddTeam.afterAddTeamCounter, 1)

	mmAddTeam.t.Helper()

	if mmAddTeam.inspectFuncAddTeam != nil {
		mmAddTeam.inspectFuncAddTeam(ctx, team)
	}

	mm_params := RepositoryMockAddTeamParams{ctx, team}

	// Record call args
	mmAddTeam.AddTeamMock.mutex.Lock()
	mmAddTeam.AddTeamMock.callArgs = append(mmAddTeam.AddTeamMock.callArgs, &mm_params)
	mmAddTeam.AddTeamMock.mutex.Unlock()

	for _, e := range mmAddTeam.AddTeamMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAddTeam.AddTeamMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddTeam.AddTeamMock.defaultExpectation.Counter, 1)
		mm_want := mmAddTeam.AddTeamMock.defaultExpectation.params
		mm_want_ptrs := mmAddTeam.AddTeamMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockAddTeamParams{ctx, team}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmAddTeam.t.Errorf("RepositoryMock.AddTeam got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddTeam.AddTeamMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.team != nil && !minimock.Equal(*mm_want_ptrs.team, mm_got.team) {
				mmAddTeam.t.Errorf("RepositoryMock.AddTeam got unexpected parameter team, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddTeam.AddTeamMock.defaultExpectation.expectationOrigins.originTeam, *mm_want_ptrs.team, mm_got.team, minimock.Diff(*mm_want_ptrs.team, mm_got.team))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddTeam.t.Errorf("RepositoryMock.AddTeam got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAddTeam.AddTeamMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddTeam.AddTeamMock.defaultExpectation.results
		if mm_results == nil {
			mmAddTeam.t.Fatal("No results are set for the RepositoryMock.AddTeam")
		}
		return (*mm_results).err
	}
	if mmAddTeam.funcAddTeam != nil {
		return mmAddTeam.funcAddTeam(ctx, team)
	}
	mmAddTeam.t.Fatalf("Unexpected call to RepositoryMock.AddTeam. %v %v", ctx, team)
	return
}

// AddTeamAfterCounter returns a count of finished RepositoryMock.AddTeam invocations
func (mmAddTeam *RepositoryMock) AddTeamAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddTeam.afterAddTeamCounter)
}

// AddTeamBeforeCounter returns a count of RepositoryMock.AddTeam invocations
func (mmAddTeam *RepositoryMock) AddTeamBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddTeam.beforeAddTeamCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.AddTeam.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddTeam *mRepositoryMockAddTeam) Calls() []*RepositoryMockAddTeamParams {
	mmAddTeam.mutex.RLock()

	argCopy := make([]*RepositoryMockAddTeamParams, len(mmAddTeam.callArgs))
	copy(argCopy, mmAddTeam.callArgs)

	mmAddTeam.mutex.RUnlock()

	return argCopy
}

// MinimockAddTeamDone returns true if the count of the AddTeam invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockAddTeamDone() bool {
	if m.AddTeamMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddTeamMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddTeamMock.invocationsDone()
}

// MinimockAddTeamInspect logs each unmet expectation
func (m *RepositoryMock) MinimockAddTeamInspect() {
	for _, e := range m.AddTeamMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.AddTeam at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddTeamCounter := mm_atomic.LoadUint64(&m.afterAddTeamCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddTeamMock.defaultExpectation != nil && afterAddTeamCounter < 1 {
		if m.AddTeamMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.AddTeam at\n%s", m.AddTeamMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.AddTeam at\n%s with params: %#v", m.AddTeamMock.defaultExpectation.expectationOrigins.origin, *m.AddTeamMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddTeam != nil && afterAddTeamCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.AddTeam at\n%s", m.funcAddTeamOrigin)
	}

	if !m.AddTeamMock.invocationsDone() && afterAddTeamCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.AddTeam at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddTeamMock.expectedInvocations), m.AddTeamMock.expectedInvocationsOrigin, afterAddTeamCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddTeamInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddTeamDone()
}
